---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyst(analyst)
	tools(tools)
	validate_answer(validate_answer)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyst;
	analyst -.-> tools;
	analyst -. &nbsp;__end__&nbsp; .-> validate_answer;
	tools --> analyst;
	validate_answer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
